-- Cleanup
DROP TABLE IF EXISTS teachers;
DROP TABLE IF EXISTS faculty_schedules;

-- Create Tables
CREATE TABLE teachers (
    id TEXT PRIMARY KEY,
    name TEXT NOT NULL,
    department TEXT,
    access_code TEXT UNIQUE NOT NULL
);

CREATE TABLE faculty_schedules (
    id TEXT PRIMARY KEY,
    name TEXT NOT NULL,
    department TEXT,
    schedule TEXT DEFAULT '{}'
);

-- Insert Records
INSERT INTO teachers (id, name, department, access_code) VALUES ('SLK', 'Mr. Sunil Kumar', 'Commerce', 'SLK');
INSERT INTO faculty_schedules (id, name, department) VALUES ('SLK', 'Mr. Sunil Kumar', 'Commerce');
INSERT INTO teachers (id, name, department, access_code) VALUES ('NGG', 'Dr. Nawang Gialchhin', 'Commerce', 'NGG');
INSERT INTO faculty_schedules (id, name, department) VALUES ('NGG', 'Dr. Nawang Gialchhin', 'Commerce');
INSERT INTO teachers (id, name, department, access_code) VALUES ('LVV', 'Dr. Linesh V. V.', 'Commerce', 'LVV');
INSERT INTO faculty_schedules (id, name, department) VALUES ('LVV', 'Dr. Linesh V. V.', 'Commerce');
INSERT INTO teachers (id, name, department, access_code) VALUES ('SFK', 'Dr. Shefali Kapoor', 'Commerce', 'SFK');
INSERT INTO faculty_schedules (id, name, department) VALUES ('SFK', 'Dr. Shefali Kapoor', 'Commerce');
INSERT INTO teachers (id, name, department, access_code) VALUES ('RUK', 'Prof. Ruchi Kaushik', 'Commerce', 'RUK');
INSERT INTO faculty_schedules (id, name, department) VALUES ('RUK', 'Prof. Ruchi Kaushik', 'Commerce');
INSERT INTO teachers (id, name, department, access_code) VALUES ('RHR', 'Mr. Rishabh Raj', 'Commerce', 'RHR');
INSERT INTO faculty_schedules (id, name, department) VALUES ('RHR', 'Mr. Rishabh Raj', 'Commerce');
INSERT INTO teachers (id, name, department, access_code) VALUES ('MIG', 'Dr. Misha Govil', 'Commerce', 'MIG');
INSERT INTO faculty_schedules (id, name, department) VALUES ('MIG', 'Dr. Misha Govil', 'Commerce');
INSERT INTO teachers (id, name, department, access_code) VALUES ('SIS', 'Ms. Smita Sharma', 'Corporate Laws', 'SIS');
INSERT INTO faculty_schedules (id, name, department) VALUES ('SIS', 'Ms. Smita Sharma', 'Corporate Laws');
INSERT INTO teachers (id, name, department, access_code) VALUES ('DPE', 'Prof. Deepashree', 'International Business & VAC', 'DPE');
INSERT INTO faculty_schedules (id, name, department) VALUES ('DPE', 'Prof. Deepashree', 'International Business & VAC');
INSERT INTO teachers (id, name, department, access_code) VALUES ('RNC', 'Dr. Reena Chadha', 'Event Mgmt & Company Law', 'RNC');
INSERT INTO faculty_schedules (id, name, department) VALUES ('RNC', 'Dr. Reena Chadha', 'Event Mgmt & Company Law');
INSERT INTO teachers (id, name, department, access_code) VALUES ('SLG', 'Dr. Sneh Lata Gupta', 'Cost Accounting & Mgmt', 'SLG');
INSERT INTO faculty_schedules (id, name, department) VALUES ('SLG', 'Dr. Sneh Lata Gupta', 'Cost Accounting & Mgmt');
INSERT INTO teachers (id, name, department, access_code) VALUES ('RUA', 'Ms. Renu Agarwal', 'HRM & Company Law', 'RUA');
INSERT INTO faculty_schedules (id, name, department) VALUES ('RUA', 'Ms. Renu Agarwal', 'HRM & Company Law');
INSERT INTO teachers (id, name, department, access_code) VALUES ('AMS', 'Dr. Amit Sachdeva', 'Commerce Department', 'AMS');
INSERT INTO faculty_schedules (id, name, department) VALUES ('AMS', 'Dr. Amit Sachdeva', 'Commerce Department');
INSERT INTO teachers (id, name, department, access_code) VALUES ('RAJ', 'Prof. Rachna Jawa', 'Commerce Department', 'RAJ');
INSERT INTO faculty_schedules (id, name, department) VALUES ('RAJ', 'Prof. Rachna Jawa', 'Commerce Department');
INSERT INTO teachers (id, name, department, access_code) VALUES ('AAJ', 'Prof. Aruna Jha', 'Corporate Governance & Fin Mgmt', 'AAJ');
INSERT INTO faculty_schedules (id, name, department) VALUES ('AAJ', 'Prof. Aruna Jha', 'Corporate Governance & Fin Mgmt');
INSERT INTO teachers (id, name, department, access_code) VALUES ('SSS', 'Ms. Santosh Sabharwal', 'Commerce Department', 'SSS');
INSERT INTO faculty_schedules (id, name, department) VALUES ('SSS', 'Ms. Santosh Sabharwal', 'Commerce Department');
INSERT INTO teachers (id, name, department, access_code) VALUES ('MAK', 'Prof. Mallika Kumar', 'Commerce Department', 'MAK');
INSERT INTO faculty_schedules (id, name, department) VALUES ('MAK', 'Prof. Mallika Kumar', 'Commerce Department');
INSERT INTO teachers (id, name, department, access_code) VALUES ('SNK', 'Dr. Santosh Kumar', 'Commerce Department', 'SNK');
INSERT INTO faculty_schedules (id, name, department) VALUES ('SNK', 'Dr. Santosh Kumar', 'Commerce Department');
INSERT INTO teachers (id, name, department, access_code) VALUES ('AYJ', 'Prof. Abhay Jain', 'Commerce Department', 'AYJ');
INSERT INTO faculty_schedules (id, name, department) VALUES ('AYJ', 'Prof. Abhay Jain', 'Commerce Department');
INSERT INTO teachers (id, name, department, access_code) VALUES ('SHK', 'Prof. Santosh Kumari', 'Commerce Department', 'SHK');
INSERT INTO faculty_schedules (id, name, department) VALUES ('SHK', 'Prof. Santosh Kumari', 'Commerce Department');
INSERT INTO teachers (id, name, department, access_code) VALUES ('PRD', 'Prof. Padmeshwar Doley', 'Commerce Department', 'PRD');
INSERT INTO faculty_schedules (id, name, department) VALUES ('PRD', 'Prof. Padmeshwar Doley', 'Commerce Department');
INSERT INTO teachers (id, name, department, access_code) VALUES ('HNT', 'Prof. Harendra Nath Tiwari', 'Commerce Department', 'HNT');
INSERT INTO faculty_schedules (id, name, department) VALUES ('HNT', 'Prof. Harendra Nath Tiwari', 'Commerce Department');
INSERT INTO teachers (id, name, department, access_code) VALUES ('TNM', 'Prof. Tarun Manjhi', 'Commerce Department', 'TNM');
INSERT INTO faculty_schedules (id, name, department) VALUES ('TNM', 'Prof. Tarun Manjhi', 'Commerce Department');
INSERT INTO teachers (id, name, department, access_code) VALUES ('SAP', 'Prof. Surya Prakash', 'Consumer Behaviour & Advertising', 'SAP');
INSERT INTO faculty_schedules (id, name, department) VALUES ('SAP', 'Prof. Surya Prakash', 'Consumer Behaviour & Advertising');
INSERT INTO teachers (id, name, department, access_code) VALUES ('NNM', 'Prof. Naveen Mittal', 'GST & Corporate Tax', 'NNM');
INSERT INTO faculty_schedules (id, name, department) VALUES ('NNM', 'Prof. Naveen Mittal', 'GST & Corporate Tax');
INSERT INTO teachers (id, name, department, access_code) VALUES ('KIJ', 'Prof. Kinneri Jain', 'Commerce Department', 'KIJ');
INSERT INTO faculty_schedules (id, name, department) VALUES ('KIJ', 'Prof. Kinneri Jain', 'Commerce Department');
INSERT INTO teachers (id, name, department, access_code) VALUES ('VAJ', 'Prof. Vandana Jain', 'Commerce Department', 'VAJ');
INSERT INTO faculty_schedules (id, name, department) VALUES ('VAJ', 'Prof. Vandana Jain', 'Commerce Department');
INSERT INTO teachers (id, name, department, access_code) VALUES ('KRA', 'Ms. Karuna', 'Commerce Department', 'KRA');
INSERT INTO faculty_schedules (id, name, department) VALUES ('KRA', 'Ms. Karuna', 'Commerce Department');
INSERT INTO teachers (id, name, department, access_code) VALUES ('MAB', 'Dr. Monika Bansal', 'Commerce Department', 'MAB');
INSERT INTO faculty_schedules (id, name, department) VALUES ('MAB', 'Dr. Monika Bansal', 'Commerce Department');
INSERT INTO teachers (id, name, department, access_code) VALUES ('ANK', 'Dr. Amanpreet Kaur', 'Sustainability Marketing & HRM', 'ANK');
INSERT INTO faculty_schedules (id, name, department) VALUES ('ANK', 'Dr. Amanpreet Kaur', 'Sustainability Marketing & HRM');
INSERT INTO teachers (id, name, department, access_code) VALUES ('AOK', 'Dr. Alok Kumar', 'Commerce Department', 'AOK');
INSERT INTO faculty_schedules (id, name, department) VALUES ('AOK', 'Dr. Alok Kumar', 'Commerce Department');
INSERT INTO teachers (id, name, department, access_code) VALUES ('ASA', 'Dr. Anisha', 'Commerce Department', 'ASA');
INSERT INTO faculty_schedules (id, name, department) VALUES ('ASA', 'Dr. Anisha', 'Commerce Department');
INSERT INTO teachers (id, name, department, access_code) VALUES ('RKS', 'Dr. Raj Kumar Sah', 'Commerce Department', 'RKS');
INSERT INTO faculty_schedules (id, name, department) VALUES ('RKS', 'Dr. Raj Kumar Sah', 'Commerce Department');
INSERT INTO teachers (id, name, department, access_code) VALUES ('SIA', 'Dr. Shalini Aggarwal', 'Commerce Department', 'SIA');
INSERT INTO faculty_schedules (id, name, department) VALUES ('SIA', 'Dr. Shalini Aggarwal', 'Commerce Department');
INSERT INTO teachers (id, name, department, access_code) VALUES ('BLK', 'Mr. Bal Kishan', 'Commerce Department', 'BLK');
INSERT INTO faculty_schedules (id, name, department) VALUES ('BLK', 'Mr. Bal Kishan', 'Commerce Department');
INSERT INTO teachers (id, name, department, access_code) VALUES ('SUY', 'Mr. Sudhanshu Yadav', 'Commerce Department', 'SUY');
INSERT INTO faculty_schedules (id, name, department) VALUES ('SUY', 'Mr. Sudhanshu Yadav', 'Commerce Department');
INSERT INTO teachers (id, name, department, access_code) VALUES ('HHK', 'Mr. Harish Kumar', 'Commerce Department', 'HHK');
INSERT INTO faculty_schedules (id, name, department) VALUES ('HHK', 'Mr. Harish Kumar', 'Commerce Department');
INSERT INTO teachers (id, name, department, access_code) VALUES ('MTS', 'Ms. Manpreet Sharma', 'Business Statistics & HRM', 'MTS');
INSERT INTO faculty_schedules (id, name, department) VALUES ('MTS', 'Ms. Manpreet Sharma', 'Business Statistics & HRM');
INSERT INTO teachers (id, name, department, access_code) VALUES ('PNM', 'Ms. Poonam', 'Commerce Department', 'PNM');
INSERT INTO faculty_schedules (id, name, department) VALUES ('PNM', 'Ms. Poonam', 'Commerce Department');
INSERT INTO teachers (id, name, department, access_code) VALUES ('PAA', 'Dr. Priyanka Aggarwal', 'Commerce Department', 'PAA');
INSERT INTO faculty_schedules (id, name, department) VALUES ('PAA', 'Dr. Priyanka Aggarwal', 'Commerce Department');
INSERT INTO teachers (id, name, department, access_code) VALUES ('MDH', 'Mr. Mohd. Hassan', 'International Business & Company Law', 'MDH');
INSERT INTO faculty_schedules (id, name, department) VALUES ('MDH', 'Mr. Mohd. Hassan', 'International Business & Company Law');
INSERT INTO teachers (id, name, department, access_code) VALUES ('VAK', 'Ms. Vartika Khandelwal', 'Commerce Department', 'VAK');
INSERT INTO faculty_schedules (id, name, department) VALUES ('VAK', 'Ms. Vartika Khandelwal', 'Commerce Department');
INSERT INTO teachers (id, name, department, access_code) VALUES ('JDP', 'Dr. Jaideep', 'Commerce Department', 'JDP');
INSERT INTO faculty_schedules (id, name, department) VALUES ('JDP', 'Dr. Jaideep', 'Commerce Department');
INSERT INTO teachers (id, name, department, access_code) VALUES ('AAR', 'Dr. Asha Rani', 'GST & Business Stats', 'AAR');
INSERT INTO faculty_schedules (id, name, department) VALUES ('AAR', 'Dr. Asha Rani', 'GST & Business Stats');
INSERT INTO teachers (id, name, department, access_code) VALUES ('JTW', 'Dr. Jigmet Wangdus', 'Corp. Governance & Intl. Business', 'JTW');
INSERT INTO faculty_schedules (id, name, department) VALUES ('JTW', 'Dr. Jigmet Wangdus', 'Corp. Governance & Intl. Business');
INSERT INTO teachers (id, name, department, access_code) VALUES ('YAM', 'Dr. Yusra Naseem', 'Commerce Department', 'YAM');
INSERT INTO faculty_schedules (id, name, department) VALUES ('YAM', 'Dr. Yusra Naseem', 'Commerce Department');
INSERT INTO teachers (id, name, department, access_code) VALUES ('AUV', 'Ms. Anju Verma', 'Commerce Department', 'AUV');
INSERT INTO faculty_schedules (id, name, department) VALUES ('AUV', 'Ms. Anju Verma', 'Commerce Department');
INSERT INTO teachers (id, name, department, access_code) VALUES ('SVP', 'Dr. Shashank Vikram Pratap Singh', 'Intl. Business & HRM', 'SVP');
INSERT INTO faculty_schedules (id, name, department) VALUES ('SVP', 'Dr. Shashank Vikram Pratap Singh', 'Intl. Business & HRM');
INSERT INTO teachers (id, name, department, access_code) VALUES ('DAB', 'Dr. Dipika Bansal', 'Commerce Department', 'DAB');
INSERT INTO faculty_schedules (id, name, department) VALUES ('DAB', 'Dr. Dipika Bansal', 'Commerce Department');
INSERT INTO teachers (id, name, department, access_code) VALUES ('PRA', 'Dr. Prerana', 'Commerce Department', 'PRA');
INSERT INTO faculty_schedules (id, name, department) VALUES ('PRA', 'Dr. Prerana', 'Commerce Department');
INSERT INTO teachers (id, name, department, access_code) VALUES ('SHG', 'Dr. Saurabh Gupta', 'Commerce Department', 'SHG');
INSERT INTO faculty_schedules (id, name, department) VALUES ('SHG', 'Dr. Saurabh Gupta', 'Commerce Department');
INSERT INTO teachers (id, name, department, access_code) VALUES ('SAA', 'Dr. Saumya Aggarwal', 'Business Analytics', 'SAA');
INSERT INTO faculty_schedules (id, name, department) VALUES ('SAA', 'Dr. Saumya Aggarwal', 'Business Analytics');
INSERT INTO teachers (id, name, department, access_code) VALUES ('ATS', 'Dr. Amarjeet Singh', 'Commerce Department', 'ATS');
INSERT INTO faculty_schedules (id, name, department) VALUES ('ATS', 'Dr. Amarjeet Singh', 'Commerce Department');
INSERT INTO teachers (id, name, department, access_code) VALUES ('STS', 'Mr. Satnam Singh', 'Commerce Department', 'STS');
INSERT INTO faculty_schedules (id, name, department) VALUES ('STS', 'Mr. Satnam Singh', 'Commerce Department');
INSERT INTO teachers (id, name, department, access_code) VALUES ('SJJ', 'Dr. Saroj Joshi', 'Commerce Department', 'SJJ');
INSERT INTO faculty_schedules (id, name, department) VALUES ('SJJ', 'Dr. Saroj Joshi', 'Commerce Department');
INSERT INTO teachers (id, name, department, access_code) VALUES ('AJJ', 'Dr. Anuj Jatav', 'EXIM & Corp. Governance', 'AJJ');
INSERT INTO faculty_schedules (id, name, department) VALUES ('AJJ', 'Dr. Anuj Jatav', 'EXIM & Corp. Governance');
INSERT INTO teachers (id, name, department, access_code) VALUES ('DTY', 'Dr. Dixit Yadav', 'Commerce Department', 'DTY');
INSERT INTO faculty_schedules (id, name, department) VALUES ('DTY', 'Dr. Dixit Yadav', 'Commerce Department');
INSERT INTO teachers (id, name, department, access_code) VALUES ('AAT', 'Ms. Ankita Tomar', 'Commerce Department', 'AAT');
INSERT INTO faculty_schedules (id, name, department) VALUES ('AAT', 'Ms. Ankita Tomar', 'Commerce Department');
INSERT INTO teachers (id, name, department, access_code) VALUES ('VIC', 'Ms. Vaishali Chhokar', 'Commerce Department', 'VIC');
INSERT INTO faculty_schedules (id, name, department) VALUES ('VIC', 'Ms. Vaishali Chhokar', 'Commerce Department');
INSERT INTO teachers (id, name, department, access_code) VALUES ('ATK', 'Dr. Amit Kumar', 'Business Stats & GST', 'ATK');
INSERT INTO faculty_schedules (id, name, department) VALUES ('ATK', 'Dr. Amit Kumar', 'Business Stats & GST');
INSERT INTO teachers (id, name, department, access_code) VALUES ('SNS', 'Dr. Suman Si', 'Commerce Department', 'SNS');
INSERT INTO faculty_schedules (id, name, department) VALUES ('SNS', 'Dr. Suman Si', 'Commerce Department');
INSERT INTO teachers (id, name, department, access_code) VALUES ('GVR', 'Mr. Gaurav Rana', 'Commerce Department', 'GVR');
INSERT INTO faculty_schedules (id, name, department) VALUES ('GVR', 'Mr. Gaurav Rana', 'Commerce Department');
INSERT INTO teachers (id, name, department, access_code) VALUES ('PKK', 'Dr. Palak Kanojia', 'Commerce Department', 'PKK');
INSERT INTO faculty_schedules (id, name, department) VALUES ('PKK', 'Dr. Palak Kanojia', 'Commerce Department');
INSERT INTO teachers (id, name, department, access_code) VALUES ('AAA', 'Dr. Anuradha Aggarwal', 'Commerce Department', 'AAA');
INSERT INTO faculty_schedules (id, name, department) VALUES ('AAA', 'Dr. Anuradha Aggarwal', 'Commerce Department');
INSERT INTO teachers (id, name, department, access_code) VALUES ('RAC', 'Dr. Ruchika Choudhary', 'Commerce Department', 'RAC');
INSERT INTO faculty_schedules (id, name, department) VALUES ('RAC', 'Dr. Ruchika Choudhary', 'Commerce Department');
INSERT INTO teachers (id, name, department, access_code) VALUES ('RAS', 'Dr. Rutika Saini', 'Corp. Governance & Business Ethics', 'RAS');
INSERT INTO faculty_schedules (id, name, department) VALUES ('RAS', 'Dr. Rutika Saini', 'Corp. Governance & Business Ethics');
INSERT INTO teachers (id, name, department, access_code) VALUES ('KKS', 'Dr. Kamaldeep Kaur Sarna', 'Commerce Department', 'KKS');
INSERT INTO faculty_schedules (id, name, department) VALUES ('KKS', 'Dr. Kamaldeep Kaur Sarna', 'Commerce Department');
INSERT INTO teachers (id, name, department, access_code) VALUES ('PAC', 'Dr. Priya Chaurasia', 'Commerce Department', 'PAC');
INSERT INTO faculty_schedules (id, name, department) VALUES ('PAC', 'Dr. Priya Chaurasia', 'Commerce Department');
INSERT INTO teachers (id, name, department, access_code) VALUES ('AVB', 'Mr. Anuj Vijay Bhatia', 'Corp. Governance & Finance', 'AVB');
INSERT INTO faculty_schedules (id, name, department) VALUES ('AVB', 'Mr. Anuj Vijay Bhatia', 'Corp. Governance & Finance');
INSERT INTO teachers (id, name, department, access_code) VALUES ('CUS', 'Dr. Charu Shri', 'Commerce Department', 'CUS');
INSERT INTO faculty_schedules (id, name, department) VALUES ('CUS', 'Dr. Charu Shri', 'Commerce Department');
INSERT INTO teachers (id, name, department, access_code) VALUES ('NJA', 'Dr. Nikunj Aggarwal', 'Commerce Department', 'NJA');
INSERT INTO faculty_schedules (id, name, department) VALUES ('NJA', 'Dr. Nikunj Aggarwal', 'Commerce Department');
INSERT INTO teachers (id, name, department, access_code) VALUES ('AKY', 'Mr. Abhishek Kumar Yadav', 'Commerce Department', 'AKY');
INSERT INTO faculty_schedules (id, name, department) VALUES ('AKY', 'Mr. Abhishek Kumar Yadav', 'Commerce Department');
INSERT INTO teachers (id, name, department, access_code) VALUES ('ALK', 'Mr. Anil Kumar', 'Commerce Department', 'ALK');
INSERT INTO faculty_schedules (id, name, department) VALUES ('ALK', 'Mr. Anil Kumar', 'Commerce Department');
INSERT INTO teachers (id, name, department, access_code) VALUES ('SIM', 'Dr. Shruti Mallik', 'Commerce Department', 'SIM');
INSERT INTO faculty_schedules (id, name, department) VALUES ('SIM', 'Dr. Shruti Mallik', 'Commerce Department');
INSERT INTO teachers (id, name, department, access_code) VALUES ('SAG', 'Dr. Shikha Gupta', 'Commerce Department', 'SAG');
INSERT INTO faculty_schedules (id, name, department) VALUES ('SAG', 'Dr. Shikha Gupta', 'Commerce Department');
INSERT INTO teachers (id, name, department, access_code) VALUES ('AAG', 'Ms. Anubha Godara', 'Advertising & Business Analytics', 'AAG');
INSERT INTO faculty_schedules (id, name, department) VALUES ('AAG', 'Ms. Anubha Godara', 'Advertising & Business Analytics');
INSERT INTO teachers (id, name, department, access_code) VALUES ('LKB', 'Ms. Latika Bajetha', 'Commerce Department', 'LKB');
INSERT INTO faculty_schedules (id, name, department) VALUES ('LKB', 'Ms. Latika Bajetha', 'Commerce Department');
INSERT INTO teachers (id, name, department, access_code) VALUES ('SAR', 'Dr. Shikha Rajput', 'Commerce Department', 'SAR');
INSERT INTO faculty_schedules (id, name, department) VALUES ('SAR', 'Dr. Shikha Rajput', 'Commerce Department');
INSERT INTO teachers (id, name, department, access_code) VALUES ('VIS', 'Mr. Vikki Sharma', 'Commerce Department', 'VIS');
INSERT INTO faculty_schedules (id, name, department) VALUES ('VIS', 'Mr. Vikki Sharma', 'Commerce Department');
INSERT INTO teachers (id, name, department, access_code) VALUES ('NAD', 'Dr. Nisha Devi', 'Commerce Department', 'NAD');
INSERT INTO faculty_schedules (id, name, department) VALUES ('NAD', 'Dr. Nisha Devi', 'Commerce Department');
INSERT INTO teachers (id, name, department, access_code) VALUES ('KNK', 'Mr. Krishan Kant', 'Commerce Department', 'KNK');
INSERT INTO faculty_schedules (id, name, department) VALUES ('KNK', 'Mr. Krishan Kant', 'Commerce Department');
INSERT INTO teachers (id, name, department, access_code) VALUES ('SPB', 'Dr. Sapna Bansal', 'Commerce Department', 'SPB');
INSERT INTO faculty_schedules (id, name, department) VALUES ('SPB', 'Dr. Sapna Bansal', 'Commerce Department');
INSERT INTO teachers (id, name, department, access_code) VALUES ('SVK', 'Dr. Shivangi Kaushik', 'Commerce Department', 'SVK');
INSERT INTO faculty_schedules (id, name, department) VALUES ('SVK', 'Dr. Shivangi Kaushik', 'Commerce Department');
INSERT INTO teachers (id, name, department, access_code) VALUES ('RJ', 'Dr. Rajiv Jha', 'Commerce Department', 'RJ');
INSERT INTO faculty_schedules (id, name, department) VALUES ('RJ', 'Dr. Rajiv Jha', 'Commerce Department');
INSERT INTO teachers (id, name, department, access_code) VALUES ('RUR', 'Prof. Ritu Ranjan', 'Commerce Department', 'RUR');
INSERT INTO faculty_schedules (id, name, department) VALUES ('RUR', 'Prof. Ritu Ranjan', 'Commerce Department');
INSERT INTO teachers (id, name, department, access_code) VALUES ('PB', 'Ms. Priyanka Bhatia', 'Intro Econometrics', 'PB');
INSERT INTO faculty_schedules (id, name, department) VALUES ('PB', 'Ms. Priyanka Bhatia', 'Intro Econometrics');
INSERT INTO teachers (id, name, department, access_code) VALUES ('ENN', 'Dr. Esther Ngaihte', 'Commerce Department', 'ENN');
INSERT INTO faculty_schedules (id, name, department) VALUES ('ENN', 'Dr. Esther Ngaihte', 'Commerce Department');
INSERT INTO teachers (id, name, department, access_code) VALUES ('AKJ', 'Dr. Avinash Kumar Jha', 'Commerce Department', 'AKJ');
INSERT INTO faculty_schedules (id, name, department) VALUES ('AKJ', 'Dr. Avinash Kumar Jha', 'Commerce Department');
INSERT INTO teachers (id, name, department, access_code) VALUES ('RB', 'Dr. Renu Bansal', 'Commerce Department', 'RB');
INSERT INTO faculty_schedules (id, name, department) VALUES ('RB', 'Dr. Renu Bansal', 'Commerce Department');
INSERT INTO teachers (id, name, department, access_code) VALUES ('RAK', 'Dr. Rakesh Ranjan', 'Commerce Department', 'RAK');
INSERT INTO faculty_schedules (id, name, department) VALUES ('RAK', 'Dr. Rakesh Ranjan', 'Commerce Department');
INSERT INTO teachers (id, name, department, access_code) VALUES ('NG', 'Ms. Nidhi Gupta', 'Commerce Department', 'NG');
INSERT INTO faculty_schedules (id, name, department) VALUES ('NG', 'Ms. Nidhi Gupta', 'Commerce Department');
INSERT INTO teachers (id, name, department, access_code) VALUES ('RK', 'Dr. Ravi Kant', 'Commerce Department', 'RK');
INSERT INTO faculty_schedules (id, name, department) VALUES ('RK', 'Dr. Ravi Kant', 'Commerce Department');
INSERT INTO teachers (id, name, department, access_code) VALUES ('RHT', 'Mr. Rohit', 'Commerce Department', 'RHT');
INSERT INTO faculty_schedules (id, name, department) VALUES ('RHT', 'Mr. Rohit', 'Commerce Department');
INSERT INTO teachers (id, name, department, access_code) VALUES ('KD', 'Dr. Kapil Dev Yadav', 'Commerce Department', 'KD');
INSERT INTO faculty_schedules (id, name, department) VALUES ('KD', 'Dr. Kapil Dev Yadav', 'Commerce Department');
INSERT INTO teachers (id, name, department, access_code) VALUES ('YAA', 'Ms. Yuthika Agarwal', 'Commerce Department', 'YAA');
INSERT INTO faculty_schedules (id, name, department) VALUES ('YAA', 'Ms. Yuthika Agarwal', 'Commerce Department');
INSERT INTO teachers (id, name, department, access_code) VALUES ('CG', 'Ms. Chhavi Gautam', 'Commerce Department', 'CG');
INSERT INTO faculty_schedules (id, name, department) VALUES ('CG', 'Ms. Chhavi Gautam', 'Commerce Department');
INSERT INTO teachers (id, name, department, access_code) VALUES ('JK', 'Mr. Jagadish Konthoujam', 'Commerce Department', 'JK');
INSERT INTO faculty_schedules (id, name, department) VALUES ('JK', 'Mr. Jagadish Konthoujam', 'Commerce Department');
INSERT INTO teachers (id, name, department, access_code) VALUES ('AK', 'Mr. Ashwani Kumar', 'Intro Macroeconomics', 'AK');
INSERT INTO faculty_schedules (id, name, department) VALUES ('AK', 'Mr. Ashwani Kumar', 'Intro Macroeconomics');
INSERT INTO teachers (id, name, department, access_code) VALUES ('AG', 'Dr. Amit Girdharwal', 'Commerce Department', 'AG');
INSERT INTO faculty_schedules (id, name, department) VALUES ('AG', 'Dr. Amit Girdharwal', 'Commerce Department');
INSERT INTO teachers (id, name, department, access_code) VALUES ('AGD', 'Ms. Anuradha Gulati Dasgupta', 'Commerce Department', 'AGD');
INSERT INTO faculty_schedules (id, name, department) VALUES ('AGD', 'Ms. Anuradha Gulati Dasgupta', 'Commerce Department');
INSERT INTO teachers (id, name, department, access_code) VALUES ('ABK', 'Mr. Abhishek Khadgawat', 'Commerce Department', 'ABK');
INSERT INTO faculty_schedules (id, name, department) VALUES ('ABK', 'Mr. Abhishek Khadgawat', 'Commerce Department');
INSERT INTO teachers (id, name, department, access_code) VALUES ('HA', 'Ms. Himanshi Aggarwal', 'Commerce Department', 'HA');
INSERT INTO faculty_schedules (id, name, department) VALUES ('HA', 'Ms. Himanshi Aggarwal', 'Commerce Department');
INSERT INTO teachers (id, name, department, access_code) VALUES ('SHS', 'Ms. Shreya Shreedhar', 'Indian Economy & Macro', 'SHS');
INSERT INTO faculty_schedules (id, name, department) VALUES ('SHS', 'Ms. Shreya Shreedhar', 'Indian Economy & Macro');
INSERT INTO teachers (id, name, department, access_code) VALUES ('KK', 'Dr. Kaushal Kishore', 'Commerce Department', 'KK');
INSERT INTO faculty_schedules (id, name, department) VALUES ('KK', 'Dr. Kaushal Kishore', 'Commerce Department');
INSERT INTO teachers (id, name, department, access_code) VALUES ('MG', 'Dr. Monika Gaur', 'Commerce Department', 'MG');
INSERT INTO faculty_schedules (id, name, department) VALUES ('MG', 'Dr. Monika Gaur', 'Commerce Department');
INSERT INTO teachers (id, name, department, access_code) VALUES ('AKS', 'Dr. Avnish Kumar Sharma', 'Mathematics Department', 'AKS');
INSERT INTO faculty_schedules (id, name, department) VALUES ('AKS', 'Dr. Avnish Kumar Sharma', 'Mathematics Department');