CREATE TABLE IF NOT EXISTS teachers (id TEXT PRIMARY KEY, name TEXT NOT NULL, department TEXT, access_code TEXT UNIQUE);
DELETE FROM teachers;
INSERT INTO teachers (id, name, department, access_code) VALUES ('ID_MSPOONAM', 'Ms. Poonam', 'Commerce', 'ACCT_ID_MSPOONAM_1561');
INSERT INTO teachers (id, name, department, access_code) VALUES ('ID_DRPRIYANKAAGGARWAL', 'Dr. Priyanka Aggarwal', 'Commerce', 'ACCT_ID_DRPRIYANKAAGGARWAL_4838');
INSERT INTO teachers (id, name, department, access_code) VALUES ('ID_MRMOHDHASSAN', 'Mr. Mohd. Hassan', 'Commerce', 'ACCT_ID_MRMOHDHASSAN_1152');
INSERT INTO teachers (id, name, department, access_code) VALUES ('ID_MSVARTIKAKHANDELWAL', 'Ms. Vartika Khandelwal', 'Commerce', 'ACCT_ID_MSVARTIKAKHANDELWAL_8820');
INSERT INTO teachers (id, name, department, access_code) VALUES ('ID_DRJAIDEEP', 'Dr. Jaideep', 'Commerce', 'ACCT_ID_DRJAIDEEP_7507');
INSERT INTO teachers (id, name, department, access_code) VALUES ('ID_DRASHARANI', 'Dr. Asha Rani', 'Commerce', 'ACCT_ID_DRASHARANI_5874');
INSERT INTO teachers (id, name, department, access_code) VALUES ('ID_DRJIGMETWANGDUS', 'Dr. Jigmet Wangdus', 'Commerce', 'ACCT_ID_DRJIGMETWANGDUS_6828');
INSERT INTO teachers (id, name, department, access_code) VALUES ('ID_DRYUSRANASEEM', 'Dr. Yusra Naseem', 'Commerce', 'ACCT_ID_DRYUSRANASEEM_1740');
INSERT INTO teachers (id, name, department, access_code) VALUES ('ID_MSANJUVERMA', 'Ms. Anju Verma', 'Commerce', 'ACCT_ID_MSANJUVERMA_823');
INSERT INTO teachers (id, name, department, access_code) VALUES ('ID_DRSHASHANKVIKRAMPRATAPSINGH', 'Dr. Shashank Vikram Pratap Singh', 'Commerce', 'ACCT_ID_DRSHASHANKVIKRAMPRATAPSINGH_1689');
INSERT INTO teachers (id, name, department, access_code) VALUES ('ID_DRDIPIKABANSAL', 'Dr. Dipika Bansal', 'Commerce', 'ACCT_ID_DRDIPIKABANSAL_2571');
INSERT INTO teachers (id, name, department, access_code) VALUES ('ID_DRPRERANA', 'Dr. Prerana', 'Commerce', 'ACCT_ID_DRPRERANA_8753');
INSERT INTO teachers (id, name, department, access_code) VALUES ('ID_DRSAURABHGUPTA', 'Dr. Saurabh Gupta', 'Commerce', 'ACCT_ID_DRSAURABHGUPTA_7236');
INSERT INTO teachers (id, name, department, access_code) VALUES ('ID_DRSAUMYAAGGARWAL', 'Dr. Saumya Aggarwal', 'Commerce', 'ACCT_ID_DRSAUMYAAGGARWAL_9721');
INSERT INTO teachers (id, name, department, access_code) VALUES ('ID_DRAMARJEETSINGH', 'Dr. Amarjeet Singh', 'Commerce', 'ACCT_ID_DRAMARJEETSINGH_8235');
INSERT INTO teachers (id, name, department, access_code) VALUES ('ID_MRSATNAMSINGH', 'Mr. Satnam Singh', 'Commerce', 'ACCT_ID_MRSATNAMSINGH_3964');
INSERT INTO teachers (id, name, department, access_code) VALUES ('ID_DRSAROJJOSHI', 'Dr. Saroj Joshi', 'Commerce', 'ACCT_ID_DRSAROJJOSHI_177');
INSERT INTO teachers (id, name, department, access_code) VALUES ('ID_DRANUJJATAV', 'Dr. Anuj Jatav', 'Commerce', 'ACCT_ID_DRANUJJATAV_9139');
INSERT INTO teachers (id, name, department, access_code) VALUES ('ID_DRDIXITYADAV', 'Dr. Dixit Yadav', 'Commerce', 'ACCT_ID_DRDIXITYADAV_6288');
INSERT INTO teachers (id, name, department, access_code) VALUES ('ID_MSANKITATOMAR', 'Ms. Ankita Tomar', 'Commerce', 'ACCT_ID_MSANKITATOMAR_6261');
INSERT INTO teachers (id, name, department, access_code) VALUES ('ID_MSVAISHALICHHOKAR', 'Ms. Vaishali Chhokar', 'Commerce', 'ACCT_ID_MSVAISHALICHHOKAR_9441');
INSERT INTO teachers (id, name, department, access_code) VALUES ('ID_MRHIMANSHUPALPURI', 'Mr. Himanshu Palpuri', 'Commerce', 'ACCT_ID_MRHIMANSHUPALPURI_8918');
INSERT INTO teachers (id, name, department, access_code) VALUES ('ID_DRNEETUSAMAL', 'Dr. Neetu Samal', 'Commerce', 'ACCT_ID_DRNEETUSAMAL_5176');
INSERT INTO teachers (id, name, department, access_code) VALUES ('ID_MRSHIVAMKUSHWAHA', 'Mr. Shivam Kushwaha', 'Commerce', 'ACCT_ID_MRSHIVAMKUSHWAHA_8429');
INSERT INTO teachers (id, name, department, access_code) VALUES ('ID_DRMITHUNPANT', 'Dr. Mithun Pant', 'Commerce', 'ACCT_ID_DRMITHUNPANT_1240');
INSERT INTO teachers (id, name, department, access_code) VALUES ('ID_MSANUJ', 'Ms. Anuj', 'Commerce', 'ACCT_ID_MSANUJ_4513');
INSERT INTO teachers (id, name, department, access_code) VALUES ('ID_MSSHALINIKAWAL', 'Ms. Shalini Kawal', 'Commerce', 'ACCT_ID_MSSHALINIKAWAL_7545');
INSERT INTO teachers (id, name, department, access_code) VALUES ('ID_DRANJALIAGARWAL', 'Dr. Anjali Agarwal', 'Commerce', 'ACCT_ID_DRANJALIAGARWAL_5347');
INSERT INTO teachers (id, name, department, access_code) VALUES ('ID_DRSONIADEVI', 'Dr. Sonia Devi', 'Commerce', 'ACCT_ID_DRSONIADEVI_7860');
INSERT INTO teachers (id, name, department, access_code) VALUES ('ID_MRDINESHCHAND', 'Mr. Dinesh Chand', 'Commerce', 'ACCT_ID_MRDINESHCHAND_382');
INSERT INTO teachers (id, name, department, access_code) VALUES ('ID_DRRENUKA', 'Dr. Renuka', 'Commerce', 'ACCT_ID_DRRENUKA_2592');
INSERT INTO teachers (id, name, department, access_code) VALUES ('ID_DRPREETI', 'Dr. Preeti', 'Commerce', 'ACCT_ID_DRPREETI_2346');
INSERT INTO teachers (id, name, department, access_code) VALUES ('ID_MRANUJYADAV', 'Mr. Anuj Yadav', 'Commerce', 'ACCT_ID_MRANUJYADAV_8465');
INSERT INTO teachers (id, name, department, access_code) VALUES ('ID_DRREERUPREETIKAUR', 'Dr. Reerupreeti Kaur', 'Commerce', 'ACCT_ID_DRREERUPREETIKAUR_8674');
INSERT INTO teachers (id, name, department, access_code) VALUES ('ID_DRNAVINJAIN', 'Dr. Navin Jain', 'Commerce', 'ACCT_ID_DRNAVINJAIN_1854');
INSERT INTO teachers (id, name, department, access_code) VALUES ('ID_MRVARDANKUSHWAHA', 'Mr. Vardan Kushwaha', 'Commerce', 'ACCT_ID_MRVARDANKUSHWAHA_4106');
INSERT INTO teachers (id, name, department, access_code) VALUES ('ID_DRDEEPASHRI', 'Dr. Deepashri', 'Commerce', 'ACCT_ID_DRDEEPASHRI_6197');
INSERT INTO teachers (id, name, department, access_code) VALUES ('ID_DRCHARUGOEL', 'Dr. Charu Goel', 'Commerce', 'ACCT_ID_DRCHARUGOEL_9401');
INSERT INTO teachers (id, name, department, access_code) VALUES ('ID_DRREERU', 'Dr. Reeru', 'Commerce', 'ACCT_ID_DRREERU_4292');
INSERT INTO teachers (id, name, department, access_code) VALUES ('ID_DRRECHUGOPAL', 'Dr. Rechu Gopal', 'Commerce', 'ACCT_ID_DRRECHUGOPAL_3830');
INSERT INTO teachers (id, name, department, access_code) VALUES ('ID_DRSANTOSHKUMAR', 'Dr. Santosh Kumar', 'Commerce', 'ACCT_ID_DRSANTOSHKUMAR_4048');
INSERT INTO teachers (id, name, department, access_code) VALUES ('ID_DRRAJNIAGRAWAL', 'Dr. Rajni Agrawal', 'Commerce', 'ACCT_ID_DRRAJNIAGRAWAL_6132');
INSERT INTO teachers (id, name, department, access_code) VALUES ('ID_DRMUKESHAGARWAL', 'Dr. Mukesh Agarwal', 'Commerce', 'ACCT_ID_DRMUKESHAGARWAL_6813');
INSERT INTO teachers (id, name, department, access_code) VALUES ('ID_DRSUNITASAMEERPUBBY', 'Dr. Sunita Sameer Pubby', 'Commerce', 'ACCT_ID_DRSUNITASAMEERPUBBY_4390');
INSERT INTO teachers (id, name, department, access_code) VALUES ('ID_DRALOKKUMAR', 'Dr. Alok Kumar', 'Commerce', 'ACCT_ID_DRALOKKUMAR_353');
INSERT INTO teachers (id, name, department, access_code) VALUES ('ID_DRANILKUMAR', 'Dr. Anil Kumar', 'Commerce', 'ACCT_ID_DRANILKUMAR_5060');
INSERT INTO teachers (id, name, department, access_code) VALUES ('ID_DRRAVIMINHAS', 'Dr. Ravi Minhas', 'Commerce', 'ACCT_ID_DRRAVIMINHAS_5547');
INSERT INTO teachers (id, name, department, access_code) VALUES ('ID_DRRAKESHABHICHANDANI', 'Dr. Rakesha Bhichandani', 'Commerce', 'ACCT_ID_DRRAKESHABHICHANDANI_7682');
INSERT INTO teachers (id, name, department, access_code) VALUES ('ID_MSASHA', 'Ms. Asha', 'Commerce', 'ACCT_ID_MSASHA_3665');
INSERT INTO teachers (id, name, department, access_code) VALUES ('ID_DRPRADEEP', 'Dr. Pradeep', 'Commerce', 'ACCT_ID_DRPRADEEP_7448');
INSERT INTO teachers (id, name, department, access_code) VALUES ('ID_DRPRADEEPKUMAR', 'Dr. Pradeep Kumar', 'Commerce', 'ACCT_ID_DRPRADEEPKUMAR_3931');
INSERT INTO teachers (id, name, department, access_code) VALUES ('ID_DRRUCHISINGH', 'Dr. Ruchi Singh', 'Commerce', 'ACCT_ID_DRRUCHISINGH_8902');
INSERT INTO teachers (id, name, department, access_code) VALUES ('ID_DRKHEMLATA', 'Dr. Khemlata', 'Commerce', 'ACCT_ID_DRKHEMLATA_1324');
INSERT INTO teachers (id, name, department, access_code) VALUES ('ID_DRVIBHAJAIN', 'Dr. Vibha Jain', 'Commerce', 'ACCT_ID_DRVIBHAJAIN_8686');
INSERT INTO teachers (id, name, department, access_code) VALUES ('ID_DRPRASHANTVATS', 'Dr. Prashant Vats', 'Commerce', 'ACCT_ID_DRPRASHANTVATS_3003');
INSERT INTO teachers (id, name, department, access_code) VALUES ('ID_DRASTHAARORA', 'Dr. Astha Arora', 'Commerce', 'ACCT_ID_DRASTHAARORA_9764');
INSERT INTO teachers (id, name, department, access_code) VALUES ('ID_DRRAJEEVKUMAR', 'Dr. Rajeev Kumar', 'Commerce', 'ACCT_ID_DRRAJEEVKUMAR_6496');
INSERT INTO teachers (id, name, department, access_code) VALUES ('ID_DRNEHAABROL', 'Dr. Neha Abrol', 'Commerce', 'ACCT_ID_DRNEHAABROL_593');
INSERT INTO teachers (id, name, department, access_code) VALUES ('ID_DRGOPALPUNIA', 'Dr. Gopal Punia', 'Commerce', 'ACCT_ID_DRGOPALPUNIA_6858');
INSERT INTO teachers (id, name, department, access_code) VALUES ('ID_DRTARUN', 'Dr. Tarun', 'Commerce', 'ACCT_ID_DRTARUN_5093');
INSERT INTO teachers (id, name, department, access_code) VALUES ('ID_DRAABHA', 'Dr. Aabha', 'Commerce', 'ACCT_ID_DRAABHA_151');
INSERT INTO teachers (id, name, department, access_code) VALUES ('ID_DRGEETA', 'Dr. Geeta', 'Commerce', 'ACCT_ID_DRGEETA_610');
INSERT INTO teachers (id, name, department, access_code) VALUES ('ID_DRGEETASHARMA', 'Dr. Geeta Sharma', 'Commerce', 'ACCT_ID_DRGEETASHARMA_8077');
INSERT INTO teachers (id, name, department, access_code) VALUES ('ID_DRPRIYANKAKUMARI', 'Dr. Priyanka Kumari', 'Commerce', 'ACCT_ID_DRPRIYANKAKUMARI_8141');
INSERT INTO teachers (id, name, department, access_code) VALUES ('ID_DRSHIKHAYADAV', 'Dr. Shikha Yadav', 'Commerce', 'ACCT_ID_DRSHIKHAYADAV_4689');
INSERT INTO teachers (id, name, department, access_code) VALUES ('ID_DRSARITA', 'Dr. Sarita', 'Commerce', 'ACCT_ID_DRSARITA_9144');
INSERT INTO teachers (id, name, department, access_code) VALUES ('ID_DRSUNITASHARMA', 'Dr. Sunita Sharma', 'Commerce', 'ACCT_ID_DRSUNITASHARMA_1602');
INSERT INTO teachers (id, name, department, access_code) VALUES ('ID_DRSAKSHI', 'Dr. Sakshi', 'Commerce', 'ACCT_ID_DRSAKSHI_3672');
INSERT INTO teachers (id, name, department, access_code) VALUES ('ID_MSARUNAJHA', 'Ms. Aruna Jha', 'Commerce', 'ACCT_ID_MSARUNAJHA_8950');
INSERT INTO teachers (id, name, department, access_code) VALUES ('ID_DRSUNITADEY', 'Dr. Sunita Dey', 'Commerce', 'ACCT_ID_DRSUNITADEY_1012');
INSERT INTO teachers (id, name, department, access_code) VALUES ('ID_DRSHAIILENDRAKUMARSINGH', 'Dr. Shailendra Kumar Singh', 'Commerce', 'ACCT_ID_DRSHAIILENDRAKUMARSINGH_7947');
INSERT INTO teachers (id, name, department, access_code) VALUES ('ID_DRMUKESHKUMAR', 'Dr. Mukesh Kumar', 'Commerce', 'ACCT_ID_DRMUKESHKUMAR_3068');
INSERT INTO teachers (id, name, department, access_code) VALUES ('ID_DRMALTI', 'Dr. Malti', 'Commerce', 'ACCT_ID_DRMALTI_3856');
INSERT INTO teachers (id, name, department, access_code) VALUES ('ID_DRKULBIR', 'Dr. Kulbir', 'Commerce', 'ACCT_ID_DRKULBIR_941');
INSERT INTO teachers (id, name, department, access_code) VALUES ('ID_DRSUNITASAMEER', 'Dr. Sunita Sameer', 'Commerce', 'ACCT_ID_DRSUNITASAMEER_8033');
INSERT INTO teachers (id, name, department, access_code) VALUES ('ID_DRNISHARANA', 'Dr. Nisha Rana', 'Commerce', 'ACCT_ID_DRNISHARANA_8564');
INSERT INTO teachers (id, name, department, access_code) VALUES ('ID_DRRAVIMINHASCOMMERCE', 'Dr. Ravi Minhas (Commerce)', 'Commerce', 'ACCT_ID_DRRAVIMINHASCOMMERCE_6760');
INSERT INTO teachers (id, name, department, access_code) VALUES ('ID_DRMEENAKSHI', 'Dr. Meenakshi', 'Commerce', 'ACCT_ID_DRMEENAKSHI_2823');
INSERT INTO teachers (id, name, department, access_code) VALUES ('ID_DRSNEHLATA', 'Dr. Sneh Lata', 'Commerce', 'ACCT_ID_DRSNEHLATA_229');
INSERT INTO teachers (id, name, department, access_code) VALUES ('ID_DRSANTOSHKUMARCOMMERCE', 'Dr. Santosh Kumar (Commerce)', 'Commerce', 'ACCT_ID_DRSANTOSHKUMARCOMMERCE_6297');
INSERT INTO teachers (id, name, department, access_code) VALUES ('ID_DRMUKESH', 'Dr. Mukesh', 'Commerce', 'ACCT_ID_DRMUKESH_7529');
INSERT INTO teachers (id, name, department, access_code) VALUES ('ID_MRRSBHARDWAJ', 'Mr. R. S. Bhardwaj', 'Commerce', 'ACCT_ID_MRRSBHARDWAJ_495');
INSERT INTO teachers (id, name, department, access_code) VALUES ('ID_MRJAGADISHKONTHOUJAM', 'Mr. Jagadish Konthoujam', 'Commerce', 'ACCT_ID_MRJAGADISHKONTHOUJAM_5035');
INSERT INTO teachers (id, name, department, access_code) VALUES ('ID_MRASHWANIKUMAR', 'Mr. Ashwani Kumar', 'Commerce', 'ACCT_ID_MRASHWANIKUMAR_1558');
INSERT INTO teachers (id, name, department, access_code) VALUES ('ID_DRAMITGIRDHARWAL', 'Dr. Amit Girdharwal', 'Commerce', 'ACCT_ID_DRAMITGIRDHARWAL_4384');
INSERT INTO teachers (id, name, department, access_code) VALUES ('ID_MSANURADHAGULATIDASGUPTA', 'Ms. Anuradha Gulati Dasgupta', 'Commerce', 'ACCT_ID_MSANURADHAGULATIDASGUPTA_5446');
INSERT INTO teachers (id, name, department, access_code) VALUES ('ID_MRABHISHEKKHADGAWAT', 'Mr. Abhishek Khadgawat', 'Commerce', 'ACCT_ID_MRABHISHEKKHADGAWAT_6441');
INSERT INTO teachers (id, name, department, access_code) VALUES ('ID_MSHIMANSHIAGGARWAL', 'Ms. Himanshi Aggarwal', 'Commerce', 'ACCT_ID_MSHIMANSHIAGGARWAL_4693');
INSERT INTO teachers (id, name, department, access_code) VALUES ('ID_MSSHREYASHREEDHAR', 'Ms. Shreya Shreedhar', 'Commerce', 'ACCT_ID_MSSHREYASHREEDHAR_2647');
INSERT INTO teachers (id, name, department, access_code) VALUES ('ID_DRKAUSHALKISHORE', 'Dr. Kaushal Kishore', 'Commerce', 'ACCT_ID_DRKAUSHALKISHORE_1598');
INSERT INTO teachers (id, name, department, access_code) VALUES ('ID_DRMONIKAGAUR', 'Dr. Monika Gaur', 'Commerce', 'ACCT_ID_DRMONIKAGAUR_6163');